### ISSUE TITLE
Tiling interrupted after moving window between screens with keyboard shortcut

### ISSUE THREAD

**Issue by willowew** [zeroxoneafour/kwin-autotile#12]
Using either Window to Previous screen or Window to Next Screen as a keyboard shortcut, it moves the window to the other screen but doesn't resume tiling on the next screen and instead goes into floating mode. It also leaves the space it previously occupied empty on the previous monitor, where the remaining windows don't expand and fill out the available space. Expected behaviour would be that the window that is changing screen adapt and tile, while the window that don't change screen also adapts and take up the remaining place.

![Before](https://user-images.githubusercontent.com/95316750/227722193-de141074-fe22-41d4-b292-7b70bb628de5.png)
![After](https://user-images.githubusercontent.com/95316750/227722207-f9bd55ef-1374-4e21-85c8-381781d12d60.png)

I have tried to make the panels identical across both monitors as well as making sure that each monitor used the same tiling layout (4 identical rectangles), neither of which had any effect on the issue.

This issue might be similar to #2.

Tested with v1.1.0.

**Comment by zeroxoneafour** [comment]
This error is expected as I do not have any code in the script for handling two separate screens. The reason for this is that I do not own two separate screens and therefore cannot test the feature.

I can try to come up with something

**Comment by zeroxoneafour** [comment]
Can you provide a journalctl output as detailed in the faq for switching window screens?

**Comment by zeroxoneafour** [comment]
It appears that switching screens does not change the virtual desktop and activate its signal. This is actually bad because the `screenChanged()` signal of the window does not have any arguments. This means that I cannot get the window that changes screen when it happens, because the `QObject::sender()` method that is needed to get the sender of a signal does not work in Javascript.

I could create a workaround by iterating through the list of clients and checking which ones have changed their screens lately, but this would be much more inefficient and a very hacky workaround for something that should be very easy.

It makes me annoyed how inconsistent and honestly poorly-thought-out KWin's scripting API is.

**Comment by zeroxoneafour** [comment]
Test the autotile.kwinscript download directly from the GitHub master branch (version should be 1.1.1) and see if it fixes anything up.

**Comment by zeroxoneafour** [comment]
Ok, good that this feature works with the update. Closing this issue, once I fix the new issue I'll probably release v1.1.1
