### ISSUE TITLE
First window spawned is maximized and goes below other tiled windows

### ISSUE THREAD

**Issue by willowew** [zeroxoneafour/kwin-autotile#16]
When spawning a new window on an empty screen, it goes full screen as expected. When adding a second window, the window that was spawned first remains full screen but goes into the background while the second window takes up a quarter of the screen (my split is an even 2x2). Adding even more windows results in that they continue to assume their position as determined by the split, not by the numbers of windows. I.e. adding a total of three windows, with the first being behind in full screen, the third window takes up the second quarter of the screen, not the other half. Hopefully, the images can explain it better. 

![Screenshot_20230329_215734](https://user-images.githubusercontent.com/95316750/228672307-7f317c28-7bac-42a6-b649-85f2c0c3eeb6.png)
![Screenshot_20230329_215841](https://user-images.githubusercontent.com/95316750/228672325-9c6d1f2f-aded-4ace-975b-b389e54bb0ee.png)
![Screenshot_20230329_215912](https://user-images.githubusercontent.com/95316750/228672335-30baf5c0-4f32-4a79-86fe-3b0014f3ea8f.png)

Log:
Mar 29 22:05:55 user kwin_wayland[27485]: js: Autotile DBG: Config Updated
Mar 29 22:05:55 user kwin_wayland[27485]: js: Autotile DBG: useWhitelist == false
Mar 29 22:05:55 user kwin_wayland[27485]: js: Autotile DBG: blacklist == krunner,yakuake,kded,polkit
Mar 29 22:05:55 user kwin_wayland[27485]: js: Autotile DBG: tilePopups == true
Mar 29 22:05:55 user kwin_wayland[27485]: js: Autotile DBG: borders == 3
Mar 29 22:05:55 user kwin_wayland[27485]: js: Autotile DBG: invertInsertion == false
Mar 29 22:05:55 user kwin_wayland[27485]: js: Autotile DBG: keepTiledBelow == true
Mar 29 22:06:04 user kwin_wayland[27485]: js: Autotile DBG: Tiling client org.kde.kate
Mar 29 22:06:06 user kwin_wayland[27485]: js: Autotile DBG: Tiling client Alacritty
Mar 29 22:06:07 user kwin_wayland[27485]: js: Autotile DBG: Tiling client Alacritty
Mar 29 22:06:08 user kwin_wayland[27485]: js: Autotile DBG: Tiling client Alacritty

This is true of several applications, not just the ones shown. After removing the window first window, having already spawned four on top, the tiling works as expected where new windows take and fill up the space correctly. This also seems to be monitor specific, so a window that is spawned first and goes full screen on one monitor, will occupy that same space (full screen and below) when moved to another monitor, even if there already were a few windows there. 

Tested with both v.1.1.0 and v.1.1.1.

**Comment by zeroxoneafour** [comment]
Oh boy is this going to be hard to debug.

I'll see if there's anything obvious in the tiling code that could cause this, but if I can't find anything then I may have to bust out an ancient dell monitor and see if I can reproduce this.

This issue is probably going to take either a day or a week to fix honestly.

**Comment by zeroxoneafour** [comment]
I feel like I have actually experienced this bug on my device before with a single screen though, so maybe if I get lucky I can find a way to reproduce it.

**Comment by zeroxoneafour** [comment]
I could not reproduce the bug with 2 monitors. Try using the latest commit autotile.kwinscript again (it fixed some stuff with adding handlers and cleaned the code a bit) and make sure that no clients have settings enabled in them to "save location" or "save geometry" or anything like that where they could relaunch in the same space.

**Comment by zeroxoneafour** [comment]
I think that I know what's happening. It would seem like the script is detecting a window in the tile one step too low, and is inserting the window into the top-left. If there was a window in the left side, it would be split. However, there is not and so it just inserts it because the script is not built around cases where it would misdetect something.

I may have to add some edge case detection to the putWindowInTile method. This may make the script slower, however, so I'll have to add a toggle in settings. If this is the cause of the issue, then it should work.

I have no idea why the script is doing this, unless the window is doing something like changing screens while the script is running, so I don't think this bug can be patched without a little overhead.

On a side note, my spring break is almost over so this patch and future fixes may take a little longer.

**Comment by zeroxoneafour** [comment]
I added a new experimental tiling system called "bottom up". As you probably know, the script currently does a breadth-first search for tiles that can be inserted into starting from the root tile. This approach can be bug-prone and inefficient, but usually provides the best results for tiling. However, with the bottom up tile search, the script starts looking for tiles at the bottom of the screen and goes up until it finds a tile that can be inserted into. Because it only rebuilds the bottom tiles when the layout is changed, this approach is faster as well.

The bottom tiles are put in a map where the keys are the root tiles, which should be different for each screen. If they are different for each screen, then this approach should work with multiple screens. Try the autotile.kwinscript from the latest commit if you can and see if it fixes anything for you.

If it doesn't, I'm honestly at a loss because I cannot find the bug that caused the breadth-first search to break in the first place.

**Comment by zeroxoneafour** [comment]
Also try the typescript build, it fixes a lot of bugs
