### ISSUE TITLE
The wrong place for new windows to appear

### ISSUE THREAD

**Issue by farline99** [zeroxoneafour/kwin-autotile#7]
before script :D
Thank you for this script. I missed auto tiling so much after upgrading to wayland-awesome 5.27. It's a pity that Bismuth died. You are my personal hero ❤️

![Screenshot_20230322_192635](https://user-images.githubusercontent.com/100877226/226973029-4e2737ae-0798-4e3a-ac0f-a007795d2e51.png)

I think that first new window has to appear at full screen, second on zone 1, and third window should appear also on zone one, but two first windows should be placed on zones 3 (first) and zones 2 (second) accordingly. Instead, what I see is first window is full screen, second window at zone 1, and third window at zone 3. I think that all new windows should appear at master zone 1 and other windows should move in order from bottom to top. I hope I explained it clearly 😁

**Comment by zeroxoneafour** [comment]
The script is not able to do this efficiently because it uses a breadth-first search method to look for splittable tiles. If inserting a tile right now could be done in x speed, using this method would shift all the tiles and make it at least x^2 times more inefficient. Another limitation of just being a script on top of a tiling feature not intended for autotiling.

**Comment by farline99** [comment]
Invert option does not make experience better, sadly. But if it is due to technical reasons, then ok ❤️😍
